import { KZ_FR_004_FUNCTIONING_BAYT_AL_MAL_RESIDUE } from "./candidates/KZ-FR-004-FUNCTIONING-BAYT-AL-MAL-RESIDUE";
import { KZ_FR_004_NO_FUNCTIONING_BAYT_AL_MAL_RADD } from "./candidates/KZ-FR-004-NO-FUNCTIONING-BAYT-AL-MAL-RADD";
import { KZ_FR_011_FATHER_BLOCKS_FULL_BROTHER } from "./candidates/KZ-FR-011-FATHER-BLOCKS-FULL-BROTHER";
import { KZ_FR_011_FATHER_BLOCKS_MATERNAL_BROTHER } from "./candidates/KZ-FR-011-FATHER-BLOCKS-MATERNAL-BROTHER";
import { KZ_FR_011_FATHER_BLOCKS_PATERNAL_BROTHER } from "./candidates/KZ-FR-011-FATHER-BLOCKS-PATERNAL-BROTHER";
import { KZ_FR_011_FATHER_BLOCKS_PATERNAL_GRANDFATHER } from "./candidates/KZ-FR-011-FATHER-BLOCKS-PATERNAL-GRANDFATHER";
import { KZ_FR_011_SON_BLOCKS_FULL_BROTHER } from "./candidates/KZ-FR-011-SON-BLOCKS-FULL-BROTHER";
import { KZ_FR_011_SON_BLOCKS_MATERNAL_BROTHER } from "./candidates/KZ-FR-011-SON-BLOCKS-MATERNAL-BROTHER";
import { KZ_FR_011_SON_BLOCKS_PATERNAL_BROTHER } from "./candidates/KZ-FR-011-SON-BLOCKS-PATERNAL-BROTHER";
import { KZ_FR_011_SON_BLOCKS_SONS_SON } from "./candidates/KZ-FR-011-SON-BLOCKS-SONS-SON";
import { KZ_FR_012_DAUGHTER_GROUP_TWO_THIRDS } from "./candidates/KZ-FR-012-DAUGHTER-GROUP-TWO-THIRDS";
import { KZ_FR_012_ONE_DAUGHTER_ONE_HALF } from "./candidates/KZ-FR-012-ONE-DAUGHTER-ONE-HALF";
import { KZ_FR_012_SON_GROUP_RESIDUARY } from "./candidates/KZ-FR-012-SON-GROUP-RESIDUARY";
import { KZ_FR_012_SONS_AND_DAUGHTERS_TWO_TO_ONE } from "./candidates/KZ-FR-012-SONS-AND-DAUGHTERS-TWO-TO-ONE";
import { KZ_FR_014_FATHER_ONE_SIXTH } from "./candidates/KZ-FR-014-FATHER-ONE-SIXTH";
import { KZ_FR_014_FATHER_ONE_SIXTH_PLUS_RESIDUE } from "./candidates/KZ-FR-014-FATHER-ONE-SIXTH-PLUS-RESIDUE";
import { KZ_FR_014_FATHER_RESIDUARY } from "./candidates/KZ-FR-014-FATHER-RESIDUARY";
import { KZ_FR_015_HUSBAND_MOTHER_FATHER } from "./candidates/KZ-FR-015-HUSBAND-MOTHER-FATHER";
import { KZ_FR_015_WIFE_MOTHER_FATHER } from "./candidates/KZ-FR-015-WIFE-MOTHER-FATHER";
import { KZ_FR_029_MULTIPLE_CLASS_CORRECTION } from "./candidates/KZ-FR-029-MULTIPLE-CLASS-CORRECTION";
import { KZ_FR_029_SINGLE_CLASS_CORRECTION } from "./candidates/KZ-FR-029-SINGLE-CLASS-CORRECTION";
import type { FunctionalMvpAtomicCandidateRule } from "./functional-mvp-candidate";

/** Research-only list. Production runtime code must use the generated production registry instead. */
export const FUNCTIONAL_MVP_CANDIDATES = [
  KZ_FR_004_FUNCTIONING_BAYT_AL_MAL_RESIDUE,
  KZ_FR_004_NO_FUNCTIONING_BAYT_AL_MAL_RADD,
  KZ_FR_011_FATHER_BLOCKS_PATERNAL_GRANDFATHER,
  KZ_FR_011_FATHER_BLOCKS_FULL_BROTHER,
  KZ_FR_011_FATHER_BLOCKS_PATERNAL_BROTHER,
  KZ_FR_011_FATHER_BLOCKS_MATERNAL_BROTHER,
  KZ_FR_011_SON_BLOCKS_SONS_SON,
  KZ_FR_011_SON_BLOCKS_FULL_BROTHER,
  KZ_FR_011_SON_BLOCKS_PATERNAL_BROTHER,
  KZ_FR_011_SON_BLOCKS_MATERNAL_BROTHER,
  KZ_FR_012_ONE_DAUGHTER_ONE_HALF,
  KZ_FR_012_DAUGHTER_GROUP_TWO_THIRDS,
  KZ_FR_012_SON_GROUP_RESIDUARY,
  KZ_FR_012_SONS_AND_DAUGHTERS_TWO_TO_ONE,
  KZ_FR_014_FATHER_ONE_SIXTH,
  KZ_FR_014_FATHER_RESIDUARY,
  KZ_FR_014_FATHER_ONE_SIXTH_PLUS_RESIDUE,
  KZ_FR_015_HUSBAND_MOTHER_FATHER,
  KZ_FR_015_WIFE_MOTHER_FATHER,
  KZ_FR_029_SINGLE_CLASS_CORRECTION,
  KZ_FR_029_MULTIPLE_CLASS_CORRECTION,
] as const satisfies readonly FunctionalMvpAtomicCandidateRule[];
